apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vault-sync.fullname" . }}
  labels:
    {{- include "vault-sync.labels" . | nindent 4 }}
data:
  vault-sync.yaml: |
    {{- toYaml .Values.vaultSync | nindent 4 }}
