name: Rust

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'  # Run workflow on version tags, e.g. v1.0.0
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  BINARY_NAME: your_binary_name  # Change this to your actual binary name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      run: cargo build --verbose --release
    
    - name: Run tests
      run: cargo test --verbose
    
    - name: Package binary
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        mkdir -p release
        cp target/release/${{ env.BINARY_NAME }} release/
        cd release && tar czf ${{ env.BINARY_NAME }}-linux-amd64.tar.gz ${{ env.BINARY_NAME }}
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          release/${{ env.BINARY_NAME }}-linux-amd64.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
